# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-07-20 16:12:38
"""
import arcpy

def Model(centerline_path):  # 模型

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Administrator\Documents\ArcGIS\Default.gdb", workspace=r"C:\Users\Administrator\Documents\ArcGIS\Default.gdb"):

        # Process: 缓冲区 (缓冲区) (analysis)
        未融合道路面 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面"
        arcpy.analysis.Buffer(in_features=centerline_path, out_feature_class=未融合道路面, buffer_distance_or_field="缓冲距离", line_side="FULL", line_end_type="FLAT", dissolve_option="NONE", dissolve_field=[], method="PLANAR")

        # Process: 面转线 (面转线) (management)
        红线整理 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\红线整理"
        arcpy.management.PolygonToLine(in_features=未融合道路面, out_feature_class=红线整理, neighbor_option="IDENTIFY_NEIGHBORS")

        # Process: 选择 (选择) (analysis)
        红线整理_Select = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\红线整理_Select"
        arcpy.analysis.Select(in_features=红线整理, out_feature_class=红线整理_Select, where_clause="LEFT_FID = -1")

        # Process: 标识 (2) (标识) (analysis)
        红线整理_带属性 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\红线整理_带属性"
        arcpy.analysis.Identity(in_features=红线整理_Select, identity_features=未融合道路面, out_feature_class=红线整理_带属性, join_attributes="ALL", cluster_tolerance="", relationship="NO_RELATIONSHIPS")

        # Process: 要素折点转点 (要素折点转点) (management)
        红线折点 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\红线折点"
        arcpy.management.FeatureVerticesToPoints(in_features=红线整理_带属性, out_feature_class=红线折点, point_location="BOTH_ENDS")

        # Process: 缓冲区 (2) (缓冲区) (analysis)
        折点分组缓冲 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\折点分组缓冲"
        arcpy.analysis.Buffer(in_features=红线折点, out_feature_class=折点分组缓冲, buffer_distance_or_field="1 Meters", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: 多部件至单部件 (多部件至单部件) (management)
        折点分组缓冲_拆分 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\折点分组缓冲_拆分"
        arcpy.management.MultipartToSinglepart(in_features=折点分组缓冲, out_feature_class=折点分组缓冲_拆分)

        # Process: 标识 (标识) (analysis)
        折点分组 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\折点分组"
        arcpy.analysis.Identity(in_features=红线折点, identity_features=折点分组缓冲_拆分, out_feature_class=折点分组, join_attributes="ALL", cluster_tolerance="", relationship="NO_RELATIONSHIPS")

        # Process: 缓冲区 (3) (缓冲区) (analysis)
        分组缓冲 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\分组缓冲"
        arcpy.analysis.Buffer(in_features=折点分组, out_feature_class=分组缓冲, buffer_distance_or_field="DJJL", line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field=[], method="PLANAR")

        # Process: 标识 (3) (标识) (analysis)
        输出要素类 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\红线整理_带属性_Identity"
        arcpy.analysis.Identity(in_features=红线整理_带属性, identity_features=分组缓冲, out_feature_class=输出要素类, join_attributes="ALL", cluster_tolerance="", relationship="NO_RELATIONSHIPS")

        # Process: 选择 (2) (选择) (analysis)
        前两边 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\前两边"
        arcpy.analysis.Select(in_features=输出要素类, out_feature_class=前两边, where_clause="RIGHT_FID = RIGHT_FID_1")

        # Process: 融合 (融合) (management)
        前两边_Dissolve = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\前两边_Dissolve"
        arcpy.management.Dissolve(in_features=前两边, out_feature_class=前两边_Dissolve, dissolve_field=["FID_折点分组缓冲_拆分"], statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

        # Process: 要素折点转点 (2) (要素折点转点) (management)
        倒角点 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角点"
        arcpy.management.FeatureVerticesToPoints(in_features=前两边_Dissolve, out_feature_class=倒角点, point_location="BOTH_ENDS")

        # Process: 点集转线 (点集转线) (management)
        倒角线 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角线"
        arcpy.management.PointsToLine(Input_Features=倒角点, Output_Feature_Class=倒角线, Line_Field="FID_折点分组缓冲_拆分", Sort_Field="", Close_Line="CLOSE")

        # Process: 要素转面 (要素转面) (management)
        倒角三角形 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角三角形"
        arcpy.management.FeatureToPolygon(in_features=[前两边, 倒角线], out_feature_class=倒角三角形, cluster_tolerance="", attributes="ATTRIBUTES", label_features="")

        # Process: 融合 (3) (融合) (management)
        倒角三角形融合整理 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角三角形融合整理"
        arcpy.management.Dissolve(in_features=倒角三角形, out_feature_class=倒角三角形融合整理, dissolve_field=[], statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

        # Process: 多部件至单部件 (2) (多部件至单部件) (management)
        输出要素类_2_ = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角三角形融合整理_MultipartToSinglep"
        arcpy.management.MultipartToSinglepart(in_features=倒角三角形融合整理, out_feature_class=输出要素类_2_)

        # Process: 空间连接 (空间连接) (analysis)
        倒角三角形_空间连接 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角三角形_空间连接"
        arcpy.analysis.SpatialJoin(target_features=输出要素类_2_, join_features=未融合道路面, out_feature_class=倒角三角形_空间连接, join_operation="JOIN_ONE_TO_MANY", join_type="KEEP_ALL", field_mapping="Layer \"Layer\" true true false 254 Text 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,Layer,0,254;HXKD \"HXKD\" true true false 4 Float 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,HXKD,-1,-1;缓冲距离 \"缓冲距离\" true true false 8 Double 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,缓冲距离,-1,-1;开发边界内 \"开发边界内\" true true false 2 Short 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,开发边界内,-1,-1;DJJL \"DJJL\" true true false 4 Long 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,DJJL,-1,-1;BUFF_DIST \"BUFF_DIST\" true true false 8 Double 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,BUFF_DIST,-1,-1;ORIG_FID \"ORIG_FID\" true true false 4 Long 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,ORIG_FID,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\未融合道路面,Shape_Area,-1,-1", match_option="SHARE_A_LINE_SEGMENT_WITH", search_radius="", distance_field_name="")

        # Process: 融合 (2) (融合) (management)
        倒角三角形_筛选1 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角三角形_筛选1"
        arcpy.management.Dissolve(in_features=倒角三角形_空间连接, out_feature_class=倒角三角形_筛选1, dissolve_field=["TARGET_FID"], statistics_fields=[["Join_Count", "SUM"]], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

        # Process: 选择 (3) (选择) (analysis)
        倒角三角形_筛选2 = "E:\\DataBase_本地更新库\\ZJ\\徐闻控规\\徐闻控规.gdb\\倒角三角形_筛选2"
        arcpy.analysis.Select(in_features=倒角三角形_筛选1, out_feature_class=倒角三角形_筛选2, where_clause="SUM_Join_Count <> 1")

if __name__ == '__main__':
    Model()

